### ISSUE TITLE
v2.4.0. ignores dark mode

### ISSUE THREAD

**Issue by WebShapedBiz** [elementary/switchboard#156]
With version 2.4.0. Switchboard and all plugins stoped using dark mode. Until now, everything was working just fine. The rest of the Pantheon remained dark.

![Slika zaslona 2020-05-01 10 37 06](https://user-images.githubusercontent.com/6765137/80793588-d51d2100-8b97-11ea-90d8-4e57b2d63eab.jpeg)
![Slika zaslona 2020-05-01 10 37 20](https://user-images.githubusercontent.com/6765137/80793603-dc442f00-8b97-11ea-8bb9-11ce39cc4e17.jpeg)
![Slika zaslona 2020-05-01 10 38 45](https://user-images.githubusercontent.com/6765137/80793643-f41bb300-8b97-11ea-922d-66bec1f62cec.jpeg)

- [ ] I'm using the latest version from git that I've manually compiled
- [x] I'm using the latest released stable version

I'm not using any theme, just a dark variant of elemenantaryOS. OS nor any other packages were compiled, all were installed from the official sources and deb repos. No Snaps nor Flatpaks in the system either.

Cheers.

**Comment by ryonakano** [comment]
This is because the way to set dark style differs between official one (which is not released yet) and elementary Tweaks. And specifically, [this line](https://github.com/elementary/switchboard/blob/636d2ff4c88dfec9389984b71004632f89d93793/src/Application.vala#L143) is the cause of this issue. It overrides the value of `gtk_settings.gtk_application_prefer_dark_theme` and thus only System Settings uses the light style even if we set `gtk_settings.gtk_application_prefer_dark_theme` to `true` to enable the dark style system widely in elementary Tweaks.

See also: elementary-tweaks/elementary-tweaks#146

**Comment by WebShapedBiz** [comment]
Thank you @ryonakano for your clarification.
