### ISSUE TITLE
Sound Settings disappearing

### ISSUE THREAD

**Issue by mblarsen** [elementary/switchboard#46]
The *Sound Settings* has disappeared from the panel.

Selecting *Sound Settings* from the sound icon leads to the settings panel and not into the settings.

![settings-tab](https://user-images.githubusercontent.com/247048/29739195-7a6c5ba8-8a6a-11e7-884a-6173421a68c8.jpeg)

**Comment by mblarsen** [comment]
I reinstalled `switchboard-sound` and it returned. No clue as to why it disappeared in the first place.

**Comment by tetebueno** [comment]
Hi, I don't know if this is a way to "reopen" an issue, or if I just report this back. Thing is that since a recent update Sound settings has dissappeared. When trying to reinstall (now `switchboard-plug-gcc-sound`) I get the following:

```
~$ sudo aptitude install switchboard-plug-gcc-sound
The following NEW packages will be installed:
  dconf-cli{a} gir1.2-ibus-1.0{a} ibus{ab} switchboard-plug-gcc-sound unity-control-center{a} 
0 packages upgraded, 5 newly installed, 0 to remove and 0 not upgraded.
Need to get 2.117 kB/2.183 kB of archives. After unpacking 13,1 MB will be used.
The following packages have unmet dependencies:
 ibus : Breaks: libglib2.0-0 (< 2.48.2-0ubuntu4.5~) but 2.48.2-0ubuntu4.1+elementary0.4.1 is installed.
        Breaks: libglib2.0-0:i386 (< 2.48.2-0ubuntu4.5~) but 2.48.2-0ubuntu4.1+elementary0.4.1 is installed.
The following actions will resolve these dependencies:

     Keep the following packages at their current version:
1)     ibus [Not Installed]                               
2)     switchboard-plug-gcc-sound [Not Installed]         
3)     unity-control-center [Not Installed]               

     Leave the following dependencies unresolved:         
4)     unity-control-center recommends ibus (>= 1.5.0)    


Accept this solution? [Y/n/q/?]
```
I wouldn't want to mess around with dependencies like suggested [here](https://elementaryos.stackexchange.com/questions/23965/switchboard-plug-gcc-sound-unmet-dependencies) before asking in the right place.

Please, let me know if this requires opening a new issue.

Cheers.

P.S.: Some system info:

```
~$ lsb_release -a
No LSB modules are available.
Distributor ID:	elementary
Description:	elementary OS 0.4.1 Loki
Release:	0.4.1
Codename:	loki
~$ uname -a
Linux Something 4.15.0-96-lowlatency #97~16.04.1-Ubuntu SMP PREEMPT Wed Apr 1 04:30:54 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
```
